name: CBD # 动作名称

on: # 触发条件：在push到main分支后
  push:
    branches:
      - main

jobs: # 任务
  cbd: # 任务ID
    name: doc cbd # 任务名称(检出C构建B部署D)
    runs-on: ubuntu-latest # 虚拟机环境
    steps: # 运行步骤
      # 切换Node环境
      - name: Toggle
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
      # 打包文件
      - name: Build
        run: cd docs && npm i && npm run build
      # 部署站点
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/dist/build # 打包文件位置
